### ISSUE TITLE
Feature: Reload image list

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#505]
### Describe the solution you'd like
Add support for a separated feature called _Reload image list_ would help a lot!
- Feature location: _Main menu > Reload image list_
- Shortcut: <kbd>Ctrl+Shift+F5</kbd>
- Action: 
  - Reindex the image files using loading order in settings
  - Skip caching

### Todos:
- [x] Add `Reload image list` menu
- [x] Create function `GetFilesByDistinctDirs()`
- [x] Add language string for `Reload image list` menu
- [x] Support reloading multiple folders for `Reload image list` menu
- [x] Support reloading multiple folders for changing image order
- [x] Support reloading multiple folders for changing file extensions
- [x] Merge `Repare()` and `RepareMulti()`
- [x] Allow to load multiple targets of shortcut files

**Comment by fire-eggs** [comment]
Um, I've never found this to be true. I change the sort order and can see the position of the current image change in the list. The new position is always correct for the new sort order.

**Comment by d2phap** [comment]
Oh yeah, I realized the sort order updating was already implemented.

But it's good to have `Reload image list`, cuz we had `Reload image`.
Reusing `PrepareMulti()` will be okay

**Comment by d2phap** [comment]
This feature is shipped in the latest ImageGlass Moon https://imageglass.org/moon
