### ISSUE TITLE
Feature: Go to (enhancement)

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#506]
### Goals
- Develop the Go to feature to be like an all-in-one navigation. 
- User can navigate to the image by index number, filename.
- Display image thumbnail in the search list for more accurate.

### Todos:
- [ ] **Using index number**
  - Syntax: `:<number>`
    - `:` is prefix to search by index
    - `<number>` is the index of image
  - Example: 
    - `:27` - navigate to the 27th image in the list

- [ ] **Using regular expression**
  - Syntax: `/<regex>`
    - `/` is prefix to search by regular expression
    - `<regex>` is regular expression content
  - Example:
    - `/.*\.jpg$` returns a list of the file names that end with `.jpg` (case sensitive).

- [ ] **Using file name**
  - Syntax: `<string>`
    - `<string>` is filename of the image
  - Example:
    - `summer` returns a list of the file names that contain `summer` (non case sensitive).

**Comment by d2phap** [comment]
No plan
